config/routes.rb
VotingApp::Application.routes.draw do
  resources :events, :path => 'admin/events' do
  collection do
   put 'choose'
  end
  end
  
  match 'votes' => 'events#to_be_voted'
  match 'votes/vote' => 'votes#vote'
  match 'votes/update' => 'votes#update'
  
  get 'votes/revote_error'

end

app/models/event.rb
class Event < ActiveRecord::Base
  CHOOSE=["yes", "no"]
  
  attr_accessible :event
  has_many :votes
  
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :event_id, :number, :option
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def new
		@event=Event.new
    @vote=Vote.new
		@title="New Event"
	end
	
	def index
		@events = Event.all
		@title = "Events"
  	end
  	
  	def create
  		@event = Event.new(params[:event])
  		@event.save
  		params[:vote][:options].split("####").each do |o|
  		@vote = @event.votes.build(:option => o)
  		@vote.save
  		
  		end
      
  		#if @event.save
  		    # flash message here
  		#else
  		#   @title = "New Event"
  		#   render new
  		#end
  		@events = Event.all
  		render 'events/index'
  	end
	
	def choose
		@events = Event.all
		if params[:event_ids] != nil
			Event.update_all "choose=1", :id => params[:event_ids]
			Event.update_all "choose=0", ["id not in (?)", params[:event_ids]]
		else
			Event.update_all "choose=0"
		end
	end
	
	def to_be_voted
	     @events = Event.where(["choose = ?", 1]).all
	     render 'votes/index'
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
@@ipList=[] 
	def vote 
		@event = Event.find(params[:event_id])
		@options = Vote.where(["event_id = (?)", params[:event_id]]).all
		render 'votes/vote'
	end
	
	def update
	
	@@ipList.each do |item|
		if (item == request.remote_ip)
			render'votes/revote_error'
			return
		end
	end
	
		@@ipList << request.remote_ip 
	
		Vote.update_all "number=number+1", :id => params[:vote_id]
    @event = Event.find(Vote.find(params[:vote_id]).event_id)
    @options = Vote.where(["event_id=(?)", @event.id]).all
		render 'votes/update'			
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/choose.html.erb
<h1>All Events</h1>
<% form_tag choose_events_path, :method => :put do %>
<%= @events %>
  <ul>
  <% for event in @events %>
    <li>
      <%= check_box_tag "event_ids[]", event.id %>
      <%= event.event %>
    </li>
  <% end %>
  </ul>
  <%= submit_tag "Mark as Complete" %>
<% end %>

app/views/events/index.html.erb
<h1>All Events</h1>
	<%= form_tag '/admin/events/choose', :method => :put do %>
		<ul>
			<% for event in @events %>
				<li>
					<%= check_box_tag "event_ids[]", event.id, (event.choose==1) %>
					<%= event.event %>
				</li>
			<% end %>
		</ul>
		<%= submit_tag "Update with choose" %>
	<% end %>

app/views/events/new.html.erb
<script language="javascript">
  var seperator='####'
  fields=0;
  function addOption() {
      fields++;
      //document.getElementById("text").innerHTML = document.getElementById("text").innerHTML += "option" + fields + ": <input id='option'+fields name='vote[option'+fields+']' size='30' type='text' /><br/>"
      document.getElementById("text").innerHTML = document.getElementById("text").innerHTML += "option" + fields + ": <input id=option" + fields + " name=vote[option" + fields + "] size=30 type=text /><br/>"
              //"option" + fields + ": <input field='text' value='' /><br/>"
  }
  function concatenate() {
        var temp='';
  	for(i=1; i<fields; i++) { 
  	        temp += $('#option'+i).val() + seperator;
  		//($('#option1').val() + ';'); 
  	}
  	temp += $('#option'+fields).val()
  	$('#options').val(temp)
  }
</script>
<h1>New Event</h1>
<%= form_for(@event) do |f| %>
	<div class="field">
		<%=f.label :event %><br/>
		<%=f.text_field :event %>
	</div>

    <div>
      <input type="button" onclick="addOption()" name="add" value="Add new option" />
    </div>


	<div class="action">
		<input name="commit" type="submit" value="create event" onClick="concatenate()"/>
	</div>
	
	<input type="text" id="options" name="vote[options]" value='' />
    <div id="text" />
<% end %>
<%= debug(params) if Rails.env.development? %>

app/views/events/to_be_voted.html.erb
<h1>All voting events</h1>
<ul>
<% for event in @events %>
	<li>
		<%= event.event %>
	</li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VotingApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/votes/index.html.erb
<table>
<tr>
<th>Event</th>
<th></th>
</tr>
<% @events.each do |event| %>
<tr>
<td><%= event.event %></td>
<td><%= link_to 'vote!',
      :controller => 'votes',
      :action => 'vote', 
      :event_id => event.id %></td>
</tr>
<% end %>
</table>

app/views/votes/revote_error.html.erb
Sorry, one user can only vote once!

app/views/votes/update.html.erb
<%=@event.event %>
<table>
  <% @options.each do |vote| %>
    <tr>
      <td>
        <%= vote.option %>
      </td>
      <td>
        <%= vote.number %>
      </td>
    </tr>
  <% end %>
</table>

app/views/votes/vote.html.erb
<h1><%= @event.event %></h1>
<%= form_tag '/votes/update', :method => :put do %>
		<ul>
			<% for vote in @options %>
				<li>
					<%= check_box_tag "vote_id", vote.id %>
					<%= vote.option %>
				</li>
			<% end %>
		</ul>
		<%= submit_tag "Submit vote!" %>
	<% end %>